import { compile } from 'json-schema-to-typescript';
import type { SchemaOutput } from './pathToSchema.js';

export const schemaParser = async (schema: SchemaOutput) => {
	const ts = await compile(schema.definition, 'writeTS', {
		bannerComment:
			'/* eslint-disable */\n/**\n* This file was automatically generated by path-typegen.\n* DO NOT MODIFY IT BY HAND. Instead, modify the writeTS function options parameters */',
	});

	return ts;
};
