import { compile, compileFromFile } from 'json-schema-to-typescript'
import { pathToSchema, type Options } from './__internal__/pathToSchema.js'
import { getAllFiles } from './__internal__/getAllFiles.js';
import fs from 'node:fs';

export const writeTS = async (inputPath: string, outputPath: string, options?: Options) => {
  const schema = pathToSchema(getAllFiles(inputPath));

  const res = await compile(schema.definition, 
    'writeTS',
    {
      bannerComment : "/* eslint-disable */\n/**\n* This file was automatically generated by path-typegen.\n* DO NOT MODIFY IT BY HAND. Instead, modify the writeTS function options parameters */" }
  )
 
  if (fs.existsSync(outputPath)) {
    fs.rmSync(outputPath)
  }

  fs.writeFileSync(outputPath, res)
};

